---
- name: Ensure that the SSH key exists
  digital_ocean:
    command: ssh
    state: present
    name: {{ ssh_key_name }}
    ssh_pub_key: {{ ssh_public_key }}
    api_token: {{ api_token }}
    when: (not ({{ ssh_key_name }} == "")) && (not {{ ssh_public_key }} == 0))
  register: ssh_key

- name: Ensure that the droplet exists
  digital_ocean:
    command: droplet
    state: present
    name: {{ droplet_name }}
    unique_name: yes # Ensure idempotency
    size_id: {{ size_id }}
    region_id: {{ region_id }}
    image_id: ubuntu-16-04-x64
    ssh_key_ids: {{ ssh_key.ssh_key.id }}
    api_token: {{ api_token }}
  register: droplet