---
- name: Check if SSH key exists
  local_action: command test -e ~/.ssh/{{ ssh_key_name }}
  register: ssh_key_exists
  
- name: Generate new SSH key
  local_action: command ssh-keygen -t rsa -b 4096 \
  -N {{ ssh_key_password }} \
  -f ~/.ssh/{{ ssh_key_name }}
  when: not ssh_key_exists

- name: Register the SSH key
  digital_ocean:
    command: ssh
    state: present
    name: {{ ssh_key_name }}
    ssh_pub_key: lookup('file', '~/.ssh/{{ ssh_key_name }}.pub')
    api_token: {{ api_token }}
  register: ssh_key

- name: Create a new droplet
  digital_ocean:
    command: droplet
    state: present
    name: {{ droplet_name }}
    unique_name: yes # Ensure idempotency
    size_id: {{ size_id }}
    region_id: {{ region_id }}
    image_id: {{ image_id }}
    ssh_key_ids: {{ ssh_key.ssh_key.id }}
    api_token: {{ api_token }}
  register: droplet